package org.eclipse.jt.core.impl;

public enum SqlFunction {
	COUNT, COUNT_DISTINCT, AVG, AVG_DISTINCT, SUM, SUM_DISTINCT, MAX, MIN,
	GETDATE, YEAROF, QUARTEROF, MONTHOF, WEEKOF, DAYOF, DAYOFYEAR, DAYOFWEEK,
	HOUROF, MINUTEOF, SECONDOF, MILLISECONDOF, ADDYEAR, ADDMONTH, ADDWEEK,
	ADDDAY, ADDHOUR, ADDMINUTE, ADDSECOND, ADDQUARTER, YEARDIFF, QUARTERDIFF,
	MONTHDIFF, WEEKDIFF, DAYDIFF, HOURDIFF, MINUTEDIFF, SECONDDIFF, ISLEAPYEAR,
	ISLEAPMONTH, ISLEAPDAY, SIN, COS, TAN, ASIN, ACOS, ATAN, EXP, POWER, LG,
	LN, SQRT, CEIL, FLOOR, ROUND, SIGN, ABS, CHR, NCHR, ASCII, LEN, INDEXOF,
	LOWER, UPPER, LTRIM, RTRIM, TRIM, SUBSTR, REPLACE, ROW_COUNT, NEW_RECID,
	TO_INT, TO_CHAR, BIN_TO_CHAR, BIN_LEN, BIN_SUBSTR, BIN_CONCAT, STR_CONCAT,
	GROUPING, TRUNCDAY, TRUNCMONTH, TRUNCYEAR
}
